baseurl = "https://financial-knowledge.github.io/"
title = "财经常识"
languageCode = "en-us"
copyright = "My Name"
disqusShortname = "XXX"
googleAnalytics = "XXX"
pygmentsUseClasses = true
pygmentsCodefences = true

publishDir = "docs"

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
tabWidth = 2

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = false

[author]
name = "My Name"
profile = ""

[taxonomies]
tag = "tags"

[params]
mainSections = [ "post" ]
intro = false
headline = "Ghostwriter example"
description = "Ghostwriter example description"
github = "https://github.com/XXX"
gitlab = "https://gitlab.com/XXX"
linkedin = "https://linkedin.com/in/XXX/"
twitter = "https://twitter.com/XXX"
stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
facebook = "https://www.facebook.com/username"
email = "XXX@example.com"
opengraph = true
shareTwitter = true
rss = false
shareFacebook = false
shareLinkedIn = false
dateFormat = "Mon, Jan 2, 2006"
exponeaJsUrl = ""
exponeaTarget = ""
exponeaToken = ""
exponeaTrackVisits = false
readingTime = false
readingTimeText = "预估阅读时间:"
fathomUrl = ""
fathomSiteId = ""

  [params.plausibleAnalytics]
  domain = ""
  serverURL = ""

[permalinks]
post = "/articles/:filename/"

[[menu.main]]
name = "Articles"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 2
