name: Auto deploy to gh-pages

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: cleanup files of public site
        working-directory: ./public
        shell: bash
        run: rm -rf ./*;

      - name: deploy and publish updates
        working-directory: ./public
        run: |
          git config --local user.email "jinrongcitiao@github.com"
          git config --local user.name "GitHub Action"
          git add . -A
          git commit -m "[chore] Auto publish"
          git push origin
